[package]
name = "extendr-macros"
version = "0.1.2"
authors = ["andy-thomason <andy@andythomason.com>"]
edition = "2018"
description = "Generate bindings from R to Rust."
license = "MIT"
documentation = "https://extendr.github.io/extendr/index.html"
repository = "https://github.com/extendr/extendr-macros"

[lib]
proc_macro = true

[dependencies]
syn = { version = "1.0.22", features = ["full", "extra-traits"] }
quote = "1.0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lazy_static = "1.4.0"
